import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";

// Material UI
import Box from "@mui/material/Box";
import Typography from "@mui/material/Typography";
import Grid from "@mui/material/Unstable_Grid2";
import useMediaQuery from "@mui/material/useMediaQuery";

// Components
import Icon from "./components/icon";
import Item from "./components/item";
import CustomGrid from "./components/res_grid";
import HobbiesGrid from "./components/hobbies";
import SoftSkillsGrid from "./components/soft_skills";
import TechnicalSkillsGrid from "./components/technical_skills";
import Pills from "./components/pills";
import ContactFrom from "./components/contact_form";

export default function Home() {
  const columnSettings = {
    xs: 6,
    sm: 6,
    md: 6,
  };

  // Hobbies
  const hobbyList = [
    "Financial Exploration",
    "Active Lifestyle",
    "Entertainment",
    "Travelling",
  ];

  const isSmallScreen = useMediaQuery((theme) => theme.breakpoints.down("sm"));
  
  const avatarStyle = {
    xs: isSmallScreen ? 12 : columnSettings.xs,
    sm: columnSettings.sm,
    md: columnSettings.md,
  };

  const descriptionStyle = {
    textAlign: isSmallScreen ? "center" : "left",
    fontSize: isSmallScreen ? "1rem" : "1.125rem", // Adjust font size as needed
  };

  return (
    <>
      <Head>
        <title>Portfolio Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Personal Div  */}
      <Box sx={{ flexGrow: 1, padding: 2 }}>
        <Grid container spacing={2}>
          {/* Avatar  */}
          <Grid
            {...avatarStyle}>
            <Item>
              {/* Avatar Image  */}
              <Image
                src="/images/space-dog.png"
                layout="intrinsic"
                width={100}
                height={100}
                alt="Avatar"
                style={{ borderRadius: "50%" }}
              />
            </Item>
          </Grid>

          {/* Description  */}
          <Grid
            {...avatarStyle}
            style={{
              display: "flex",
              justifyContent: "center",
              alignItems: "center",
            }}>
            <Typography variant="body1" gutterBottom sx={descriptionStyle}>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos
              blanditiis tenetur unde suscipit, quam beatae rerum inventore
              consectetur, neque doloribus, cupiditate numquam dignissimos
              laborum fugiat deleniti? Eum quasi quidem quibusdam.
            </Typography>
          </Grid>
        </Grid>
      </Box>

      {/* Hobbies  */}
      <Typography
        textAlign="center"
        variant="h3"
        sx={{ p: 3, fontWeight: "bold" }}
        gutterBottom>
        Hobbies
      </Typography>

      <HobbiesGrid id="" size={4} hobbies={hobbyList} />

      {/* Soft Skills */}
      <div id="Skills">
        <Typography
          textAlign="center"
          variant="h3"
          sx={{ p: 3, fontWeight: "bold" }}
          gutterBottom>
          Soft Skills
        </Typography>
        {/* BUG : not responsive in mobile  */}

        <SoftSkillsGrid />
      </div>

      {/* Technical Skills */}
      <Typography
        textAlign="center"
        variant="h3"
        sx={{ p: 3, fontWeight: "bold" }}
        gutterBottom>
        Technical Skills
      </Typography>

      <TechnicalSkillsGrid />

      {/* Project Showcase */}
      <div id="Projects">
        <Typography
          textAlign="center"
          variant="h3"
          sx={{ p: 3, fontWeight: "bold" }}
          gutterBottom>
          Project Showcase
        </Typography>
        <Pills />
      </div>

      {/*Contact Me */}
      <Typography
        textAlign="center"
        variant="h3"
        sx={{ p: 3, fontWeight: "bold" }}
        gutterBottom>
        Contact Me
      </Typography>
      <Typography textAlign="center" variant="h6" gutterBottom>
        Interested on my services and want to reach out then here is your chance
      </Typography>
      <ContactFrom />
    </>
  );
}
