import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
// import styles from "../styles/Home.module.css";

// Material UI
import Box from "@mui/material/Box";
import Container from "@mui/material/Container";
import Typography from "@mui/material/Typography";
import Grid from "@mui/material/Unstable_Grid2";
import useMediaQuery from "@mui/material/useMediaQuery";

// Components
import HobbiesGrid from "../components/hobbies";
import SoftSkillsGrid from "../components/soft_skills";
import TechnicalSkillsGrid from "../components/technical_skills";
import Pills from "../components/pills";
import ContactFrom from "../components/contact_form";


export default function Home() {
  const columnSettings = {
    xs: 6,
    sm: 6,
    md: 6,
  };

  // Hobbies
  const hobbyList = [
    "Financial Exploration",
    "Active Lifestyle",
    "Entertainment",
    "Travelling",
  ];

  const isSmallScreen = useMediaQuery((theme) => theme.breakpoints.down("sm"));
  const isMediumScreen = useMediaQuery((theme) => theme.breakpoints.down("md"));

  const avatarStyle = {
    xs: isSmallScreen ? 12 : columnSettings.xs,
    sm: isSmallScreen ? 12 : columnSettings.sm,
    md: columnSettings.md,
    display: "flex",
    justifyContent: "center", // Horizontally center
    alignItems: "center", // Vertically center
    height: "150rem",
    position: "relative",
  };

  const descriptionStyle = {
    textAlign: isSmallScreen ? "center" : "left",
    fontSize: isSmallScreen ? "1rem" : "1.125rem", // Adjust font size as needed
  };

  const boxPadding = {
    // Use Material-UI theme.spacing value for responsive padding
    padding: isSmallScreen ? 2 : (theme) => theme.spacing(2), // Adjust the spacing value as needed
    // paddingRight: isSmallScreen ? 2 : (theme) => theme.spacing(4),
    // paddingLeft: isSmallScreen ? 2 : (theme) => theme.spacing(2),
  };

  return (
    <Box sx={{ flexGrow: 1, backgroundColor: "#FFFFF" }}>
      <Head>
        <title>Portfolio Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Personal Div  */}
      <Box sx={{ flexGrow: 1, ...boxPadding, backgroundColor: "#FFFFFF" }}>
        <Grid container p={0} spacing={2}>
          {/* Avatar  */}
          <Grid item {...avatarStyle}>
            <Image
              src="/images/profile.png"
              layout="fill"
              objectFit="cover"
              alt="Avatar"
            />
          </Grid>

          {/* Description  */}
          <Grid item {...avatarStyle}>
            <Typography variant="body1" gutterBottom sx={descriptionStyle}>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos
              blanditiis tenetur unde suscipit, quam beatae rerum inventore
              consectetur, neque doloribus, cupiditate numquam dignissimos
              laborum fugiat deleniti? Eum quasi quidem quibusdam.
            </Typography>
          </Grid>
        </Grid>
      </Box>

      {/* Hobbies  */}
      <HobbiesGrid id="" size={4} hobbies={hobbyList} />

      {/* Soft Skills */}
      <div id="Skills">
        <SoftSkillsGrid />
      </div>

      {/* Technical Skills */}
      <TechnicalSkillsGrid />

      {/* Project Showcase */}
      <div id="Projects">
        <Box
          sx={{
            flexGrow: 1,
            padding: 2,
            py: "4rem",
            px: "3rem",
            backgroundColor: "#D3D3D3",
          }}>
          <Typography
            textAlign="center"
            variant="h3"
            sx={{ p: 3, fontWeight: "bold" }}
            gutterBottom>
            Project Showcase
          </Typography>
          <Pills />
        </Box>
      </div>

      {/*Contact Me */}
      <div id="Contact">
        <Box
          sx={{
            flexGrow: 1,
            padding: 2,
            py: "4rem",
            px: "3rem",
            backgroundColor: "#FFFFFF",
          }}>
          <Typography
            textAlign="center"
            variant="h3"
            sx={{ p: 3, fontWeight: "bold" }}
            gutterBottom>
            Contact Me
          </Typography>
          <Typography textAlign="center" variant="h6" gutterBottom>
            Interested on my services and want to reach out then here is your
            chance
          </Typography>
          <ContactFrom />
        </Box>
      </div>
    </Box>
  );
}
