import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
// import styles from "../styles/Home.module.css";

// Material UI
import Box from '@mui/material/Box';

// Components
import PersonalInfo from '../components/personal_info';
import TechnicalSkillsGrid from '../components/technical_skills';
import Services from '../components/services';


export default function Home() {
  return (
    <Box sx={{ flexGrow: 1, backgroundColor: '#FFFFF' }}>
      <Head>
        <title>Portfolio Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Personal Div  */}
      <PersonalInfo />

      {/* Technical Skills */}
      <TechnicalSkillsGrid />

      {/* Services  */}
      <Services />
    </Box>
  );
}
